### PR TITLE
Update common.sh

### PR DESCRIPTION
**Pull request by dpryan79**
I'll wait a few more minutes before merging this just to ensure that the CDN has been fully synchronized.

### CODE REVIEW

**Comment by dpryan79** [comment]
Everything should have synced by now, so I'll merge.

**Comment by dpryan79** [comment]
Awaiting feedback on https://github.com/bioconda/bioconda-utils/pull/646

**Comment by mbargull** [comment]
> v0.16.13
> - Use normal severity for uses_matplotlib lint

refs:
https://github.com/bioconda/bioconda-utils/pull/641
https://github.com/bioconda/bioconda-utils/releases/tag/v0.16.13
https://github.com/bioconda/bioconda-recipes/pull/21120

----
> v0.16.14
> - requirements: revert to conda-build=3.18.12

refs:
https://github.com/bioconda/bioconda-utils/pull/646
https://github.com/bioconda/bioconda-utils/releases/tag/v0.16.14
https://github.com/bioconda/bioconda-recipes/pull/21125

**Comment by mbargull** [comment]
The container image is up, so this can be merged. (We don't have to wait for the Conda package since we don't use it, actually.)

**Comment by dpryan79** [comment]
Thanks @mbargull !

**Pull request merged**
